name: personal_expenses
description: "A personal expense tracking app built with Flutter."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  uuid: ^4.4.2
  intl: ^0.17.0
  fl_chart: ^0.68.0
  provider: ^6.1.2
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo_name.png
    - assets/logo.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
